=== luckykiet/fuseki-testing-tool/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Dataset",
    "type": "object",
    "properties": {
        "dataset": {
            "type": "string",
            "description": "The name of the dataset."
        },
        "description": {
            "type": "string",
            "description": "A detailed description of the dataset."
        },
        "data": {
            "oneOf": [
                {
                    "type": "array",
                    "description": "An array of triples with graph information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "s": {
                                "type": "string",
                                "description": "The subject of the triple.",
                                "format": "uri"
                            },
                            "p": {
                                "type": "string",
                                "description": "The predicate of the triple.",
                                "format": "uri"
                            },
                            "o": {
                                "type": "string",
                                "description": "The object of the triple.",
                                "format": "uri"
                            },
                            "g": {
                                "type": "string",
                                "description": "The graph where the triple is located.",
                                "format": "uri"
                            }
                        },
                        "required": [
                            "s",
                            "p",
                            "o"
                        ]
                    }
                },
                {
                    "type": "string",
                    "description": "A relative file path to a dataset file containing turtle code.",
                    "minLength": 1
                }
            ]
        },
        "queries": {
            "type": "array",
            "description": "A set of SPARQL queries to interact with the dataset.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the query."
                    },
                    "description": {
                        "type": "string",
                        "description": "A detailed description of the query."
                    },
                    "sparql": {
                        "type": "string",
                        "description": "The SPARQL query string or relative path to file containing SPARQL query. Only one query should be in the file."
                    },
                    "expected": {
                        "type": "object",
                        "description": "The expected result and metadata for the query.",
                        "properties": {
                            "result": {
                                "oneOf": [
                                    {
                                        "type": "array",
                                        "description": "The expected result as an array of objects.",
                                        "items": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    {
                                        "type": "string",
                                        "description": "The expected result as a single string."
                                    },
                                    {
                                        "type": "boolean",
                                        "description": "Boolean is used for ASK queries."
                                    }
                                ]
                            },
                            "length": {
                                "type": "integer",
                                "description": "The expected number of results."
                            }
                        },
                        "anyOf": [
                            {
                                "required": [
                                    "result"
                                ]
                            },
                            {
                                "required": [
                                    "length"
                                ]
                            }
                        ]
                    }
                },
                "required": [
                    "name",
                    "description",
                    "sparql",
                    "expected"
                ]
            }
        }
    },
    "required": [
        "dataset",
        "description",
        "data",
        "queries"
    ]
}

=== luckykiet/fuseki-testing-tool/input/example_5.json
{
    "dataset": "otherOperatorsDataset",
    "description": "This is a SPARQL example demonstrating Insert, Construct, Delete, and verification queries.",
    "data": "example_5/data.ttl",
    "queries": [
        {
            "name": "Select before Insert 1",
            "description": "Verify the triple for Insert 1 not exists.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o FILTER(?s = <http://example.org/subject4> && ?p = <http://example.org/predicate4> && ?o = <http://example.org/object5>) }",
            "expected": {
                "result": [],
                "length": 0
            }
        },
        {
            "name": "Insert 1",
            "description": "Insert a new triple where the subject is 'http://example.org/subject4', predicate is 'http://example.org/predicate4', and object is 'http://example.org/object5'.",
            "sparql": "INSERT DATA { <http://example.org/subject4> <http://example.org/predicate4> <http://example.org/object5> }",
            "expected": {
                "result": "Update succeeded\n"
            }
        },
        {
            "name": "Select after Insert 1",
            "description": "Verify the inserted triple for Insert 1.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o FILTER(?s = <http://example.org/subject4> && ?p = <http://example.org/predicate4> && ?o = <http://example.org/object5>) }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject4",
                        "p": "http://example.org/predicate4",
                        "o": "http://example.org/object5"
                    }
                ],
                "length": 1
            }
        },
        {
            "name": "Select before Delete 1",
            "description": "Verify that triples with predicate 'http://example.org/predicate3' is exist.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s <http://example.org/predicate3> ?o }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject2",
                        "o": "http://example.org/object4"
                    }
                ],
                "length": 1
            }
        },
        {
            "name": "Delete 1",
            "description": "Delete triples where the predicate is 'http://example.org/predicate3'.",
            "sparql": "DELETE WHERE { ?s <http://example.org/predicate3> ?o }",
            "expected": {
                "result": "Update succeeded\n"
            }
        },
        {
            "name": "Select after Delete 1",
            "description": "Verify that triples with predicate 'http://example.org/predicate3' have been deleted.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s <http://example.org/predicate3> ?o }",
            "expected": {
                "result": [],
                "length": 0
            }
        },
        {
            "name": "Select before Delete 2",
            "description": "Check the current graph before deleting triples with object 'http://example.org/object1'.",
            "sparql": "SELECT ?s WHERE { ?s ?p <http://example.org/object1> }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1"
                    },
                    {
                        "s": "http://example.org/subject3"
                    }
                ],
                "length": 2
            }
        },
        {
            "name": "Delete 2",
            "description": "Delete all triples where the object is 'http://example.org/object1'.",
            "sparql": "DELETE WHERE { ?s ?p <http://example.org/object1> }",
            "expected": {
                "result": "Update succeeded\n"
            }
        },
        {
            "name": "Select after Delete 2",
            "description": "Verify that triples with object 'http://example.org/object1' have been deleted.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p <http://example.org/object1> }",
            "expected": {
                "result": [],
                "length": 0
            }
        },
        {
            "name": "Select before Construct 1",
            "description": "Check the current graph before constructing a new graph.",
            "sparql": "SELECT ?s ?p WHERE { ?s ?p [] . }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/predicate2"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "p": "http://example.org/predicate1"
                    },
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate2"
                    },
                    {
                        "s": "http://example.org/subject4",
                        "p": "http://example.org/predicate4"
                    }
                ],
                "length": 4
            }
        },
        {
            "name": "Construct 1",
            "description": "Construct a new graph where all subjects `<http://example.org/subject1>` and `<http://example.org/subject2>` are transformed with `newPredicate` and new type `newType`.",
            "sparql": "CONSTRUCT { ?s a <http://example.org/newType> ; <http://example.org/newPredicate> ?o } { ?s ?p ?o FILTER(?s = <http://example.org/subject1> || ?s = <http://example.org/subject2>) }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/newPredicate",
                        "o": "http://example.org/object2"
                    },
                    {
                        "s": "http://example.org/subject1",
                        "p": "rdf:type",
                        "o": "http://example.org/newType"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "p": "http://example.org/newPredicate",
                        "o": "http://example.org/object3"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "p": "rdf:type",
                        "o": "http://example.org/newType"
                    }
                ],
                "length": 4
            }
        },
        {
            "name": "Update 1",
            "description": "Update the object of all triples where the subject is 'http://example.org/subject3' to 'http://example.org/updatedObject'.",
            "sparql": "DELETE { <http://example.org/subject3> ?p ?o } INSERT { <http://example.org/subject3> ?p <http://example.org/updatedObject> } WHERE { <http://example.org/subject3> ?p ?o }",
            "expected": {
                "result": "Update succeeded\n"
            }
        },
        {
            "name": "Select after Update 1",
            "description": "Verify that the object for subject 'http://example.org/subject3' has been updated.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o FILTER(?s = <http://example.org/subject3> && ?o = <http://example.org/updatedObject>) }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate2",
                        "o": "http://example.org/updatedObject"
                    }
                ],
                "length": 1
            }
        }
    ]
}

=== luckykiet/fuseki-testing-tool/input/example_3.json
{
    "dataset": "sharedDataset",
    "description": "Example using SPARQL ASK queries to test specific conditions. Using same dataset as example_2.",
    "data": "example_2/data.ttl",
    "queries": [
        {
            "name": "Query 1",
            "description": "Check if any subject has the predicate 'http://example.org/predicate1' with the object 'http://example.org/object1'.",
            "sparql": "ASK WHERE { ?s <http://example.org/predicate1> <http://example.org/object1> }",
            "expected": {
                "result": true
            }
        },
        {
            "name": "Query 2",
            "description": "Check if there exists a triple with predicate 'http://example.org/predicate3' in the dataset.",
            "sparql": "ASK WHERE { ?s <http://example.org/predicate3> ?o }",
            "expected": {
                "result": true
            }
        },
        {
            "name": "Query 3",
            "description": "Verify if there is a subject with the object 'http://example.org/object5'.",
            "sparql": "ASK WHERE { ?s ?p <http://example.org/object5> }",
            "expected": {
                "result": true
            }
        },
        {
            "name": "Query 4",
            "description": "Confirm whether any triples exist where the object is 'http://example.org/object6'.",
            "sparql": "ASK WHERE { ?s ?p <http://example.org/object6> }",
            "expected": {
                "result": false
            }
        },
        {
            "name": "Query 5",
            "description": "Check if there exists any triple where the subject is 'http://example.org/subject3' and the predicate is not 'http://example.org/predicate4'.",
            "sparql": "ASK WHERE { <http://example.org/subject3> ?p ?o FILTER(?p != <http://example.org/predicate4>) }",
            "expected": {
                "result": true
            }
        }
    ]
}
