=== luckykiet/fuseki-testing-tool/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Dataset",
    "type": "object",
    "properties": {
        "dataset": {
            "type": "string",
            "description": "The name of the dataset."
        },
        "description": {
            "type": "string",
            "description": "A detailed description of the dataset."
        },
        "data": {
            "oneOf": [
                {
                    "type": "array",
                    "description": "An array of triples with graph information.",
                    "items": {
                        "type": "object",
                        "properties": {
                            "s": {
                                "type": "string",
                                "description": "The subject of the triple.",
                                "format": "uri"
                            },
                            "p": {
                                "type": "string",
                                "description": "The predicate of the triple.",
                                "format": "uri"
                            },
                            "o": {
                                "type": "string",
                                "description": "The object of the triple.",
                                "format": "uri"
                            },
                            "g": {
                                "type": "string",
                                "description": "The graph where the triple is located.",
                                "format": "uri"
                            }
                        },
                        "required": [
                            "s",
                            "p",
                            "o"
                        ]
                    }
                },
                {
                    "type": "string",
                    "description": "A relative file path to a dataset file containing turtle code.",
                    "minLength": 1
                }
            ]
        },
        "queries": {
            "type": "array",
            "description": "A set of SPARQL queries to interact with the dataset.",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the query."
                    },
                    "description": {
                        "type": "string",
                        "description": "A detailed description of the query."
                    },
                    "sparql": {
                        "type": "string",
                        "description": "The SPARQL query string or relative path to file containing SPARQL query. Only one query should be in the file."
                    },
                    "expected": {
                        "type": "object",
                        "description": "The expected result and metadata for the query.",
                        "properties": {
                            "result": {
                                "oneOf": [
                                    {
                                        "type": "array",
                                        "description": "The expected result as an array of objects.",
                                        "items": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    {
                                        "type": "string",
                                        "description": "The expected result as a single string."
                                    },
                                    {
                                        "type": "boolean",
                                        "description": "Boolean is used for ASK queries."
                                    }
                                ]
                            },
                            "length": {
                                "type": "integer",
                                "description": "The expected number of results."
                            }
                        },
                        "anyOf": [
                            {
                                "required": [
                                    "result"
                                ]
                            },
                            {
                                "required": [
                                    "length"
                                ]
                            }
                        ]
                    }
                },
                "required": [
                    "name",
                    "description",
                    "sparql",
                    "expected"
                ]
            }
        }
    },
    "required": [
        "dataset",
        "description",
        "data",
        "queries"
    ]
}

=== luckykiet/fuseki-testing-tool/input/runFromFileExample.json
{
    "dataset": "runFromFileExample",
    "description": "Run from turtle file example",
    "data": "runFromFileExample/data.ttl",
    "queries": [
        {
            "name": "Select before Insert 1",
            "description": "Verify the triple for Insert 1 not exists.",
            "sparql": "runFromFileExample/sparql.rq",
            "expected": {
                "result": [],
                "length": 0
            }
        },
        {
            "name": "Insert 1",
            "description": "Insert a new triple where the subject is 'http://example.org/subject4', predicate is 'http://example.org/predicate4', and object is 'http://example.org/object5'.",
            "sparql": "INSERT DATA { <http://example.org/subject4> <http://example.org/predicate4> <http://example.org/object5> }",
            "expected": {
                "result": "Update succeeded\n"
            }
        },
        {
            "name": "Select after Insert 1",
            "description": "Verify the inserted triple for Insert 1 using same SELECT command.",
            "sparql": "runFromFileExample/sparql.rq",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject4",
                        "p": "http://example.org/predicate4",
                        "o": "http://example.org/object5"
                    }
                ],
                "length": 1
            }
        },
        {
            "name": "Select total items after Insert 1",
            "description": "Compare the total number of triples after Insert 1.",
            "sparql": "SELECT ?subject ?p ?o WHERE { ?subject ?p ?o }",
            "expected": {
                "length": 7
            }
        }
    ]
}

=== luckykiet/fuseki-testing-tool/input/example_2.json
{
    "dataset": "complexDataset",
    "description": "This is a more complex SPARQL example",
    "data": [
        {
            "s": "http://example.org/subject1",
            "p": "http://example.org/predicate1",
            "o": "http://example.org/object1"
        },
        {
            "s": "http://example.org/subject1",
            "p": "http://example.org/predicate2",
            "o": "http://example.org/object2"
        },
        {
            "s": "http://example.org/subject2",
            "p": "http://example.org/predicate1",
            "o": "http://example.org/object3"
        },
        {
            "s": "http://example.org/subject2",
            "p": "http://example.org/predicate3",
            "o": "http://example.org/object4"
        },
        {
            "s": "http://example.org/subject3",
            "p": "http://example.org/predicate1",
            "o": "http://example.org/object1"
        },
        {
            "s": "http://example.org/subject3",
            "p": "http://example.org/predicate2",
            "o": "http://example.org/object3"
        }
    ],
    "queries": [
        {
            "name": "Query 1",
            "description": "Select all triples where the object is 'http://example.org/object3'.",
            "sparql": "SELECT ?s ?p WHERE { ?s ?p <http://example.org/object3> }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject2",
                        "p": "http://example.org/predicate1"
                    },
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate2"
                    }
                ],
                "length": 2
            }
        },
        {
            "name": "Query 2",
            "description": "Select subjects with a count of distinct predicates used, ordered by count descending.",
            "sparql": "SELECT ?s (COUNT(DISTINCT ?p) AS ?predicateCount) WHERE { ?s ?p ?o } GROUP BY ?s ORDER BY DESC(?predicateCount)",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1",
                        "predicateCount": "2"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "predicateCount": "2"
                    },
                    {
                        "s": "http://example.org/subject3",
                        "predicateCount": "2"
                    }
                ],
                "length": 3
            }
        },
        {
            "name": "Query 3",
            "description": "Select all subjects and objects, ordered by subject and object lexicographically.",
            "sparql": "SELECT ?s ?o WHERE { ?s ?p ?o } ORDER BY ?s ?o",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1",
                        "o": "http://example.org/object1"
                    },
                    {
                        "s": "http://example.org/subject1",
                        "o": "http://example.org/object2"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "o": "http://example.org/object3"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "o": "http://example.org/object4"
                    },
                    {
                        "s": "http://example.org/subject3",
                        "o": "http://example.org/object1"
                    },
                    {
                        "s": "http://example.org/subject3",
                        "o": "http://example.org/object3"
                    }
                ],
                "length": 6
            }
        },
        {
            "name": "Query 4",
            "description": "Select all triples where the predicate is not 'http://example.org/predicate1', ordered by object descending.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o FILTER(?p != <http://example.org/predicate1>) } ORDER BY DESC(?o)",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject2",
                        "p": "http://example.org/predicate3",
                        "o": "http://example.org/object4"
                    },
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate2",
                        "o": "http://example.org/object3"
                    },
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/predicate2",
                        "o": "http://example.org/object2"
                    }
                ],
                "length": 3
            }
        },
        {
            "name": "Query 5",
            "description": "Select all unique predicates used across the dataset.",
            "sparql": "SELECT DISTINCT ?p WHERE { ?s ?p ?o }",
            "expected": {
                "result": [
                    {
                        "p": "http://example.org/predicate1"
                    },
                    {
                        "p": "http://example.org/predicate2"
                    },
                    {
                        "p": "http://example.org/predicate3"
                    }
                ],
                "length": 3
            }
        }
    ]
}

=== luckykiet/fuseki-testing-tool/input/example_4.json
{
    "dataset": "multiGraphDataset",
    "description": "This dataset includes graph information directly in each triple using the 'g' field.",
    "data": [
        {
            "s": "http://example.org/subject1",
            "p": "http://example.org/predicate1",
            "o": "http://example.org/object1",
            "g": "http://example.org/graph1"
        },
        {
            "s": "http://example.org/subject1",
            "p": "http://example.org/predicate2",
            "o": "http://example.org/object2",
            "g": "http://example.org/graph1"
        },
        {
            "s": "http://example.org/subject2",
            "p": "http://example.org/predicate1",
            "o": "http://example.org/object3",
            "g": "http://example.org/graph2"
        },
        {
            "s": "http://example.org/subject2",
            "p": "http://example.org/predicate3",
            "o": "http://example.org/object4",
            "g": "http://example.org/graph2"
        },
        {
            "s": "http://example.org/subject3",
            "p": "http://example.org/predicate1",
            "o": "http://example.org/object1",
            "g": "http://example.org/graph3"
        },
        {
            "s": "http://example.org/subject3",
            "p": "http://example.org/predicate2",
            "o": "http://example.org/object3",
            "g": "http://example.org/graph3"
        }
    ],
    "queries": [
        {
            "name": "Query 1",
            "description": "Select all triples from graph1.",
            "sparql": "SELECT ?s ?p ?o WHERE { GRAPH <http://example.org/graph1> { ?s ?p ?o } }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/predicate1",
                        "o": "http://example.org/object1"
                    },
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/predicate2",
                        "o": "http://example.org/object2"
                    }
                ],
                "length": 2
            }
        },
        {
            "name": "Query 2",
            "description": "Select all unique subjects across all graphs.",
            "sparql": "SELECT DISTINCT ?s WHERE { GRAPH ?g { ?s ?p ?o } }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1"
                    },
                    {
                        "s": "http://example.org/subject2"
                    },
                    {
                        "s": "http://example.org/subject3"
                    }
                ],
                "length": 3
            }
        },
        {
            "name": "Query 3",
            "description": "Select all objects from graph2 where the predicate is 'http://example.org/predicate1'.",
            "sparql": "SELECT ?o WHERE { GRAPH <http://example.org/graph2> { ?s <http://example.org/predicate1> ?o } }",
            "expected": {
                "result": [
                    {
                        "o": "http://example.org/object3"
                    }
                ],
                "length": 1
            }
        },
        {
            "name": "Query 4",
            "description": "Select all triples from graph1 and graph3 where the object is 'http://example.org/object1'.",
            "sparql": "example_4/sparql_4.ttl",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/predicate1"
                    },
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate1"
                    }
                ],
                "length": 2
            }
        },
        {
            "name": "Query 5",
            "description": "Count the number of triples in each graph.",
            "sparql": "SELECT ?g (COUNT(*) AS ?tripleCount) WHERE { GRAPH ?g { ?s ?p ?o } } GROUP BY ?g",
            "expected": {
                "result": [
                    {
                        "g": "http://example.org/graph1",
                        "tripleCount": "2"
                    },
                    {
                        "g": "http://example.org/graph2",
                        "tripleCount": "2"
                    },
                    {
                        "g": "http://example.org/graph3",
                        "tripleCount": "2"
                    }
                ],
                "length": 3
            }
        }
    ]
}

=== luckykiet/fuseki-testing-tool/input/example.json
{
    "dataset": "exampleDataset",
    "description": "This is a simple SPARQL example",
    "data": [
        {
            "s": "http://example.org/subject1",
            "p": "http://example.org/predicate1",
            "o": "http://example.org/object1"
        },
        {
            "s": "http://example.org/subject3",
            "p": "http://example.org/predicate3",
            "o": "http://example.org/object3"
        },
        {
            "s": "http://example.org/subject2",
            "p": "http://example.org/predicate2",
            "o": "http://example.org/object2"
        }
    ],
    "queries": [
        {
            "name": "Query 1",
            "description": "Select all triples without sorting. The order of the triples is not guaranteed.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o }",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate3",
                        "o": "http://example.org/object3"
                    },
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/predicate1",
                        "o": "http://example.org/object1"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "p": "http://example.org/predicate2",
                        "o": "http://example.org/object2"
                    }
                ],
                "length": 3
            }
        },
        {
            "name": "Query 2",
            "description": "Select all triples sorted by subject ascending.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o } ORDER BY ?s",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/predicate1",
                        "o": "http://example.org/object1"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "p": "http://example.org/predicate2",
                        "o": "http://example.org/object2"
                    },
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate3",
                        "o": "http://example.org/object3"
                    }
                ]
            }
        },
        {
            "name": "Query 3",
            "description": "Select all triples sorted by object descending.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o } ORDER BY DESC(?o)",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate3",
                        "o": "http://example.org/object3"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "p": "http://example.org/predicate2",
                        "o": "http://example.org/object2"
                    },
                    {
                        "s": "http://example.org/subject1",
                        "p": "http://example.org/predicate1",
                        "o": "http://example.org/object1"
                    }
                ],
                "length": 3
            }
        },
        {
            "name": "Query 4",
            "description": "Select all triples sorted by object descending with limited 2.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o } ORDER BY DESC(?o) LIMIT 2",
            "expected": {
                "result": [
                    {
                        "s": "http://example.org/subject3",
                        "p": "http://example.org/predicate3",
                        "o": "http://example.org/object3"
                    },
                    {
                        "s": "http://example.org/subject2",
                        "p": "http://example.org/predicate2",
                        "o": "http://example.org/object2"
                    }
                ]
            }
        },
        {
            "name": "Query 5",
            "description": "Select all triples and compare by length.",
            "sparql": "SELECT ?s ?p ?o WHERE { ?s ?p ?o }",
            "expected": {
                "length": 3
            }
        }
    ]
}
